In [ ]:
#####################################
# IMPORTS
# Import create_engine
from sqlalchemy import create_engine
from sqlalchemy import select
from sqlalchemy import and_
from sqlalchemy import or_
from sqlalchemy import func
from sqlalchemy import case
from sqlalchemy import MetaData # this needs to creating table

#####################################
#CONNECTION TO DB
# Create an engine that connects to the db_name.sqlite file: engine
engine = create_engine('sqlite:///db_name.sqlite')

con_string = 'dialect+driver://'+'username:password'+'host:port/'+'db_name'
engine = create_engine(con_string)


# Print table names
print(engine.table_names())

# Print the column names
print(db_name.columns.keys())

# Print full table metadata
print(repr(metadata.tables['db_name']))


connection = engine.connect()
stmt = 'SELECT * FROM people'
result_proxy = connection.execute(stmt)
results = result_proxy.fetchall()
# Execute the statement and fetch the results: results
results = connection.execute(stmt).fetchall()

#####################################
# SIMPLE SELECTS

# Import select
from sqlalchemy import select

#table alias
table_alias_name = table_name.alias()

# Reflect db_name table via engine: db_name
db_name = Table('db_name', metadata, autoload=True, autoload_with=engine)

# Build select statement for db_name table: stmt
stmt = select([db_name])

# Print the emitted statement to see the SQL emitted
print(stmt)

# Execute the statement and print the results
print(connection.execute(stmt).fetchall())

first_row =  results[0]

# Print the first row of the results
print(first_row)

# Print the first column of the first row by using an index
print(first_row[0])

#join
stmt = select([func.sum(db_name.columns.colname2)])
stmt = stmt.select_from(db_name.join(colname1))
stmt = stmt.select_from(db_name.join(colname1, db_name.columns.colname3== colname1.columns.name))

# select
stmt = 'SELECT * FROM people'
stmt = select([db_name]) # select *
# where
stmt = stmt.where(or_(db_name.columns.colname1 == 'what',db_name.columns.colname1 == 'what2'))  
stmt = stmt.where(db_name.columns.colname1.startswith('New'))
stmt = stmt.where(db_name.columns.colname1.in_(colname1))
stmt = select([db_name.columns.colname1,db_name.columns.colname2])
# aggregate functions
stmt = select([func.sum(db_name.columns.colname1)])
stmt = select([func.count(db_name.columns.colname1.distinct())])
#order by
stmt = stmt.order_by(db_name.columns.colname1,db_name.columns.colname2)
ordered_stmt = stmt.order_by(desc(db_name.columns.colname1))
# new label, coulmn as
col_sum = func.sum(db_name.columns.colname1).label('new_col_name')
stmt = select([db_name.columns.colname1, col_sum])
# case
stmt = select([func.sum(
            case(
                [(db_name.columns.colname1 == 'what',
                  db_name.columns.colname2)]
            , else_=0))]) 
# cast
In [2]: stmt = select([(func.sum(
                    case(
                        [(db_name.columns.colname1 == 'what',
                          db_name.columns.colname2)]
                    , else_=0)) 
                    /
                    cast(func.sum(db_name.columns.colname2),Float) * 100)
                .label('ny_percent')]) 
#limit
stmt = stmt.limit(5)


# Loop over the results and print the age, sex, and pop2008
for result in results:
    print(result.col1, result.col2, result.col3)

for result in connection.execute(stmt):
    print(result.col1, result.col2, result.col3)
    
    
#CREATE TABLE
# Build a census table: census
census = Table('tbl_name', metadata,
               Column('colname',  String(30)),
               Column('colname2', Integer()), 
               Column('colname2', Integer()))

metadata = MetaData()

# Create the table in the database
metadata.create_all(engine)


#INSERT INTO
# Build insert statement: stmt
stmt=insert(tbl_name)

# Use values_list to insert data: results
results = connection.execute(stmt, values_list) #values_list is a list of the insertable values

# Print rowcount
print(results.rowcount)