In [2]:
import pandas as pd

In [5]:
#Read everything in one step
df = pd.read_csv("gapminder.csv")
print(df)

                                            Unnamed: 0  \
0                                                   11
1                                                   23
2                                                   35
3                                                   47
4                                                   59
5                                                   71
6                                                   83
7                                                   95
8                                                  107
9                                                  119
10                                                 131
11                                                 143
12                                                 155
13                                                 167
14                                                 179
15                                                 191
16                                                 203
17                                                 215
18                                                 227
19                                                 239
20                                                 251
21                                                 263
22                                                 275
23                                                 287
24                                                 299
25                                                 311
26                                                 323
27   335,"Congo, Dem. Rep.",2007,64606759.0,Africa,...
28   347,"Congo, Rep.",2007,3800610.0,Africa,55.322...
29                                                 359
..                                                 ...
112                                               1355
113                                               1367
114                                               1379
115                                               1391
116                                               1403
117                                               1415
118                                               1427
119                                               1439
120                                               1451
121                                               1463
122                                               1475
123                                               1487
124                                               1499
125                                               1511
126                                               1523
127                                               1535
128                                               1547
129                                               1559
130                                               1571
131                                               1583
132                                               1595
133                                               1607
134                                               1619
135                                               1631
136                                               1643
137                                               1655
138                                               1667
139  1679,"Yemen, Rep.",2007,22211743.0,Asia,62.698...
140                                               1691
141                                               1703

                      country    year    population      cont  life_exp  \
0                 Afghanistan  2007.0  3.188992e+07      Asia    43.828
1                     Albania  2007.0  3.600523e+06    Europe    76.423
2                     Algeria  2007.0  3.333322e+07    Africa    72.301
3                      Angola  2007.0  1.242048e+07    Africa    42.731
4                   Argentina  2007.0  4.030193e+07  Americas    75.320
5                   Australia  2007.0  2.043418e+07   Oceania    81.235
6                     Austria  2007.0  8.199783e+06    Europe    79.829
7                     Bahrain  2007.0  7.085730e+05      Asia    75.635
8                  Bangladesh  2007.0  1.504483e+08      Asia    64.062
9                     Belgium  2007.0  1.039223e+07    Europe    79.441
10                      Benin  2007.0  8.078314e+06    Africa    56.728
11                    Bolivia  2007.0  9.119152e+06  Americas    65.554
12     Bosnia and Herzegovina  2007.0  4.552198e+06    Europe    74.852
13                   Botswana  2007.0  1.639131e+06    Africa    50.728
14                     Brazil  2007.0  1.900106e+08  Americas    72.390
15                   Bulgaria  2007.0  7.322858e+06    Europe    73.005
16               Burkina Faso  2007.0  1.432620e+07    Africa    52.295
17                    Burundi  2007.0  8.390505e+06    Africa    49.580
18                   Cambodia  2007.0  1.413186e+07      Asia    59.723
19                   Cameroon  2007.0  1.769629e+07    Africa    50.430
20                     Canada  2007.0  3.339014e+07  Americas    80.653
21   Central African Republic  2007.0  4.369038e+06    Africa    44.741
22                       Chad  2007.0  1.023881e+07    Africa    50.651
23                      Chile  2007.0  1.628474e+07  Americas    78.553
24                      China  2007.0  1.318683e+09      Asia    72.961
25                   Colombia  2007.0  4.422755e+07  Americas    72.889
26                    Comoros  2007.0  7.109600e+05    Africa    65.152
27                        NaN     NaN           NaN       NaN       NaN
28                        NaN     NaN           NaN       NaN       NaN
29                 Costa Rica  2007.0  4.133884e+06  Americas    78.782
..                        ...     ...           ...       ...       ...
112              Sierra Leone  2007.0  6.144562e+06    Africa    42.568
113                 Singapore  2007.0  4.553009e+06      Asia    79.972
114           Slovak Republic  2007.0  5.447502e+06    Europe    74.663
115                  Slovenia  2007.0  2.009245e+06    Europe    77.926
116                   Somalia  2007.0  9.118773e+06    Africa    48.159
117              South Africa  2007.0  4.399783e+07    Africa    49.339
118                     Spain  2007.0  4.044819e+07    Europe    80.941
119                 Sri Lanka  2007.0  2.037824e+07      Asia    72.396
120                     Sudan  2007.0  4.229293e+07    Africa    58.556
121                 Swaziland  2007.0  1.133066e+06    Africa    39.613
122                    Sweden  2007.0  9.031088e+06    Europe    80.884
123               Switzerland  2007.0  7.554661e+06    Europe    81.701
124                     Syria  2007.0  1.931475e+07      Asia    74.143
125                    Taiwan  2007.0  2.317429e+07      Asia    78.400
126                  Tanzania  2007.0  3.813964e+07    Africa    52.517
127                  Thailand  2007.0  6.506815e+07      Asia    70.616
128                      Togo  2007.0  5.701579e+06    Africa    58.420
129       Trinidad and Tobago  2007.0  1.056608e+06  Americas    69.819
130                   Tunisia  2007.0  1.027616e+07    Africa    73.923
131                    Turkey  2007.0  7.115865e+07    Europe    71.777
132                    Uganda  2007.0  2.917040e+07    Africa    51.542
133            United Kingdom  2007.0  6.077624e+07    Europe    79.425
134             United States  2007.0  3.011399e+08  Americas    78.242
135                   Uruguay  2007.0  3.447496e+06  Americas    76.384
136                 Venezuela  2007.0  2.608466e+07  Americas    73.747
137                   Vietnam  2007.0  8.526236e+07      Asia    74.249
138        West Bank and Gaza  2007.0  4.018332e+06      Asia    73.422
139                       NaN     NaN           NaN       NaN       NaN
140                    Zambia  2007.0  1.174604e+07    Africa    42.384
141                  Zimbabwe  2007.0  1.231114e+07    Africa    43.487

          gdp_cap
0      974.580338
1     5937.029526
2     6223.367465
3     4797.231267
4    12779.379640
5    34435.367440
6    36126.492700
7    29796.048340
8     1391.253792
9    33692.605080
10    1441.284873
11    3822.137084
12    7446.298803
13   12569.851770
14    9065.800825
15   10680.792820
16    1217.032994
17     430.070692
18    1713.778686
19    2042.095240
20   36319.235010
21     706.016537
22    1704.063724
23   13171.638850
24    4959.114854
25    7006.580419
26     986.147879
27            NaN
28            NaN
29    9645.061420
..            ...
112    862.540756
113  47143.179640
114  18678.314350
115  25768.257590
116    926.141068
117   9269.657808
118  28821.063700
119   3970.095407
120   2602.394995
121   4513.480643
122  33859.748350
123  37506.419070
124   4184.548089
125  28718.276840
126   1107.482182
127   7458.396327
128    882.969944
129  18008.509240
130   7092.923025
131   8458.276384
132   1056.380121
133  33203.261280
134  42951.653090
135  10611.462990
136  11415.805690
137   2441.576404
138   3025.349798
139           NaN
140   1271.211593
141    469.709298

[142 rows x 7 columns]

In [8]:
#read chunk by chunk, so we read the data in manageable slice
for chunk in pd.read_csv("gapminder.csv", chunksize=10):
    print(chunk)

   Unnamed: 0      country  year   population      cont  life_exp  \
0          11  Afghanistan  2007   31889923.0      Asia    43.828
1          23      Albania  2007    3600523.0    Europe    76.423
2          35      Algeria  2007   33333216.0    Africa    72.301
3          47       Angola  2007   12420476.0    Africa    42.731
4          59    Argentina  2007   40301927.0  Americas    75.320
5          71    Australia  2007   20434176.0   Oceania    81.235
6          83      Austria  2007    8199783.0    Europe    79.829
7          95      Bahrain  2007     708573.0      Asia    75.635
8         107   Bangladesh  2007  150448339.0      Asia    64.062
9         119      Belgium  2007   10392226.0    Europe    79.441

        gdp_cap
0    974.580338
1   5937.029526
2   6223.367465
3   4797.231267
4  12779.379640
5  34435.367440
6  36126.492700
7  29796.048340
8   1391.253792
9  33692.605080
    Unnamed: 0                 country  year   population      cont  life_exp  \
10         131                   Benin  2007    8078314.0    Africa    56.728
11         143                 Bolivia  2007    9119152.0  Americas    65.554
12         155  Bosnia and Herzegovina  2007    4552198.0    Europe    74.852
13         167                Botswana  2007    1639131.0    Africa    50.728
14         179                  Brazil  2007  190010647.0  Americas    72.390
15         191                Bulgaria  2007    7322858.0    Europe    73.005
16         203            Burkina Faso  2007   14326203.0    Africa    52.295
17         215                 Burundi  2007    8390505.0    Africa    49.580
18         227                Cambodia  2007   14131858.0      Asia    59.723
19         239                Cameroon  2007   17696293.0    Africa    50.430

         gdp_cap
10   1441.284873
11   3822.137084
12   7446.298803
13  12569.851770
14   9065.800825
15  10680.792820
16   1217.032994
17    430.070692
18   1713.778686
19   2042.095240
                                           Unnamed: 0  \
20                                                251
21                                                263
22                                                275
23                                                287
24                                                299
25                                                311
26                                                323
27  335,"Congo, Dem. Rep.",2007,64606759.0,Africa,...
28  347,"Congo, Rep.",2007,3800610.0,Africa,55.322...
29                                                359

                     country    year    population      cont  life_exp  \
20                    Canada  2007.0  3.339014e+07  Americas    80.653
21  Central African Republic  2007.0  4.369038e+06    Africa    44.741
22                      Chad  2007.0  1.023881e+07    Africa    50.651
23                     Chile  2007.0  1.628474e+07  Americas    78.553
24                     China  2007.0  1.318683e+09      Asia    72.961
25                  Colombia  2007.0  4.422755e+07  Americas    72.889
26                   Comoros  2007.0  7.109600e+05    Africa    65.152
27                       NaN     NaN           NaN       NaN       NaN
28                       NaN     NaN           NaN       NaN       NaN
29                Costa Rica  2007.0  4.133884e+06  Americas    78.782

         gdp_cap
20  36319.235010
21    706.016537
22   1704.063724
23  13171.638850
24   4959.114854
25   7006.580419
26    986.147879
27           NaN
28           NaN
29   9645.061420
    Unnamed: 0             country  year  population      cont  life_exp  \
30         371       Cote d'Ivoire  2007  18013409.0    Africa    48.328
31         383             Croatia  2007   4493312.0    Europe    75.748
32         395                Cuba  2007  11416987.0  Americas    78.273
33         407      Czech Republic  2007  10228744.0    Europe    76.486
34         419             Denmark  2007   5468120.0    Europe    78.332
35         431            Djibouti  2007    496374.0    Africa    54.791
36         443  Dominican Republic  2007   9319622.0  Americas    72.235
37         455             Ecuador  2007  13755680.0  Americas    74.994
38         467               Egypt  2007  80264543.0    Africa    71.338
39         479         El Salvador  2007   6939688.0  Americas    71.878

         gdp_cap
30   1544.750112
31  14619.222720
32   8948.102923
33  22833.308510
34  35278.418740
35   2082.481567
36   6025.374752
37   6873.262326
38   5581.180998
39   5728.353514
    Unnamed: 0            country  year  population    cont  life_exp  \
40         491  Equatorial Guinea  2007    551201.0  Africa    51.579
41         503            Eritrea  2007   4906585.0  Africa    58.040
42         515           Ethiopia  2007  76511887.0  Africa    52.947
43         527            Finland  2007   5238460.0  Europe    79.313
44         539             France  2007  61083916.0  Europe    80.657
45         551              Gabon  2007   1454867.0  Africa    56.735
46         563             Gambia  2007   1688359.0  Africa    59.448
47         575            Germany  2007  82400996.0  Europe    79.406
48         587              Ghana  2007  22873338.0  Africa    60.022
49         599             Greece  2007  10706290.0  Europe    79.483

         gdp_cap
40  12154.089750
41    641.369524
42    690.805576
43  33207.084400
44  30470.016700
45  13206.484520
46    752.749726
47  32170.374420
48   1327.608910
49  27538.411880
                                           Unnamed: 0        country    year  \
50                                                611      Guatemala  2007.0
51                                                623         Guinea  2007.0
52                                                635  Guinea-Bissau  2007.0
53                                                647          Haiti  2007.0
54                                                659       Honduras  2007.0
55  671,"Hong Kong, China",2007,6980412.0,Asia,82....            NaN     NaN
56                                                683        Hungary  2007.0
57                                                695        Iceland  2007.0
58                                                707          India  2007.0
59                                                719      Indonesia  2007.0

      population      cont  life_exp       gdp_cap
50  1.257293e+07  Americas    70.259   5186.050003
51  9.947814e+06    Africa    56.007    942.654211
52  1.472041e+06    Africa    46.388    579.231743
53  8.502814e+06  Americas    60.916   1201.637154
54  7.483763e+06  Americas    70.198   3548.330846
55           NaN       NaN       NaN           NaN
56  9.956108e+06    Europe    73.338  18008.944440
57  3.019310e+05    Europe    81.757  36180.789190
58  1.110396e+09      Asia    64.698   2452.210407
59  2.235470e+08      Asia    70.650   3540.651564
                                           Unnamed: 0  country    year  \
60                                                731     Iran  2007.0
61                                                743     Iraq  2007.0
62                                                755  Ireland  2007.0
63                                                767   Israel  2007.0
64                                                779    Italy  2007.0
65                                                791  Jamaica  2007.0
66                                                803    Japan  2007.0
67                                                815   Jordan  2007.0
68                                                827    Kenya  2007.0
69  839,"Korea, Dem. Rep.",2007,23301725.0,Asia,67...      NaN     NaN

     population      cont  life_exp       gdp_cap
60   69453570.0      Asia    70.964  11605.714490
61   27499638.0      Asia    59.545   4471.061906
62    4109086.0    Europe    78.885  40675.996350
63    6426679.0      Asia    80.745  25523.277100
64   58147733.0    Europe    80.546  28569.719700
65    2780132.0  Americas    72.567   7320.880262
66  127467972.0      Asia    82.603  31656.068060
67    6053193.0      Asia    72.535   4519.461171
68   35610177.0    Africa    54.110   1463.249282
69          NaN       NaN       NaN           NaN
                                           Unnamed: 0     country    year  \
70  851,"Korea, Rep.",2007,49044790.0,Asia,78.623,...         NaN     NaN
71                                                863      Kuwait  2007.0
72                                                875     Lebanon  2007.0
73                                                887     Lesotho  2007.0
74                                                899     Liberia  2007.0
75                                                911       Libya  2007.0
76                                                923  Madagascar  2007.0
77                                                935      Malawi  2007.0
78                                                947    Malaysia  2007.0
79                                                959        Mali  2007.0

    population    cont  life_exp       gdp_cap
70         NaN     NaN       NaN           NaN
71   2505559.0    Asia    77.588  47306.989780
72   3921278.0    Asia    71.993  10461.058680
73   2012649.0  Africa    42.592   1569.331442
74   3193942.0  Africa    45.678    414.507341
75   6036914.0  Africa    73.952  12057.499280
76  19167654.0  Africa    59.443   1044.770126
77  13327079.0  Africa    48.303    759.349910
78  24821286.0    Asia    74.241  12451.655800
79  12031795.0  Africa    54.467   1042.581557
    Unnamed: 0     country  year   population      cont  life_exp  \
80         971  Mauritania  2007    3270065.0    Africa    64.164
81         983   Mauritius  2007    1250882.0    Africa    72.801
82         995      Mexico  2007  108700891.0  Americas    76.195
83        1007    Mongolia  2007    2874127.0      Asia    66.803
84        1019  Montenegro  2007     684736.0    Europe    74.543
85        1031     Morocco  2007   33757175.0    Africa    71.164
86        1043  Mozambique  2007   19951656.0    Africa    42.082
87        1055     Myanmar  2007   47761980.0      Asia    62.069
88        1067     Namibia  2007    2055080.0    Africa    52.906
89        1079       Nepal  2007   28901790.0      Asia    63.785

         gdp_cap
80   1803.151496
81  10956.991120
82  11977.574960
83   3095.772271
84   9253.896111
85   3820.175230
86    823.685621
87    944.000000
88   4811.060429
89   1091.359778
    Unnamed: 0      country  year   population      cont  life_exp  \
90        1091  Netherlands  2007   16570613.0    Europe    79.762
91        1103  New Zealand  2007    4115771.0   Oceania    80.204
92        1115    Nicaragua  2007    5675356.0  Americas    72.899
93        1127        Niger  2007   12894865.0    Africa    56.867
94        1139      Nigeria  2007  135031164.0    Africa    46.859
95        1151       Norway  2007    4627926.0    Europe    80.196
96        1163         Oman  2007    3204897.0      Asia    75.640
97        1175     Pakistan  2007  169270617.0      Asia    65.483
98        1187       Panama  2007    3242173.0  Americas    75.537
99        1199     Paraguay  2007    6667147.0  Americas    71.752

         gdp_cap
90  36797.933320
91  25185.009110
92   2749.320965
93    619.676892
94   2013.977305
95  49357.190170
96  22316.192870
97   2605.947580
98   9809.185636
99   4172.838464
     Unnamed: 0                country  year  population      cont  life_exp  \
100        1211                   Peru  2007  28674757.0  Americas    71.421
101        1223            Philippines  2007  91077287.0      Asia    71.688
102        1235                 Poland  2007  38518241.0    Europe    75.563
103        1247               Portugal  2007  10642836.0    Europe    78.098
104        1259            Puerto Rico  2007   3942491.0  Americas    78.746
105        1271                Reunion  2007    798094.0    Africa    76.442
106        1283                Romania  2007  22276056.0    Europe    72.476
107        1295                 Rwanda  2007   8860588.0    Africa    46.242
108        1307  Sao Tome and Principe  2007    199579.0    Africa    65.528
109        1319           Saudi Arabia  2007  27601038.0      Asia    72.777

          gdp_cap
100   7408.905561
101   3190.481016
102  15389.924680
103  20509.647770
104  19328.709010
105   7670.122558
106  10808.475610
107    863.088464
108   1598.435089
109  21654.831940
     Unnamed: 0          country  year  population    cont  life_exp  \
110        1331          Senegal  2007  12267493.0  Africa    63.062
111        1343           Serbia  2007  10150265.0  Europe    74.002
112        1355     Sierra Leone  2007   6144562.0  Africa    42.568
113        1367        Singapore  2007   4553009.0    Asia    79.972
114        1379  Slovak Republic  2007   5447502.0  Europe    74.663
115        1391         Slovenia  2007   2009245.0  Europe    77.926
116        1403          Somalia  2007   9118773.0  Africa    48.159
117        1415     South Africa  2007  43997828.0  Africa    49.339
118        1427            Spain  2007  40448191.0  Europe    80.941
119        1439        Sri Lanka  2007  20378239.0    Asia    72.396

          gdp_cap
110   1712.472136
111   9786.534714
112    862.540756
113  47143.179640
114  18678.314350
115  25768.257590
116    926.141068
117   9269.657808
118  28821.063700
119   3970.095407
     Unnamed: 0              country  year  population      cont  life_exp  \
120        1451                Sudan  2007  42292929.0    Africa    58.556
121        1463            Swaziland  2007   1133066.0    Africa    39.613
122        1475               Sweden  2007   9031088.0    Europe    80.884
123        1487          Switzerland  2007   7554661.0    Europe    81.701
124        1499                Syria  2007  19314747.0      Asia    74.143
125        1511               Taiwan  2007  23174294.0      Asia    78.400
126        1523             Tanzania  2007  38139640.0    Africa    52.517
127        1535             Thailand  2007  65068149.0      Asia    70.616
128        1547                 Togo  2007   5701579.0    Africa    58.420
129        1559  Trinidad and Tobago  2007   1056608.0  Americas    69.819

          gdp_cap
120   2602.394995
121   4513.480643
122  33859.748350
123  37506.419070
124   4184.548089
125  28718.276840
126   1107.482182
127   7458.396327
128    882.969944
129  18008.509240
                                            Unnamed: 0             country  \
130                                               1571             Tunisia
131                                               1583              Turkey
132                                               1595              Uganda
133                                               1607      United Kingdom
134                                               1619       United States
135                                               1631             Uruguay
136                                               1643           Venezuela
137                                               1655             Vietnam
138                                               1667  West Bank and Gaza
139  1679,"Yemen, Rep.",2007,22211743.0,Asia,62.698...                 NaN

       year   population      cont  life_exp       gdp_cap
130  2007.0   10276158.0    Africa    73.923   7092.923025
131  2007.0   71158647.0    Europe    71.777   8458.276384
132  2007.0   29170398.0    Africa    51.542   1056.380121
133  2007.0   60776238.0    Europe    79.425  33203.261280
134  2007.0  301139947.0  Americas    78.242  42951.653090
135  2007.0    3447496.0  Americas    76.384  10611.462990
136  2007.0   26084662.0  Americas    73.747  11415.805690
137  2007.0   85262356.0      Asia    74.249   2441.576404
138  2007.0    4018332.0      Asia    73.422   3025.349798
139     NaN          NaN       NaN       NaN           NaN
     Unnamed: 0   country  year  population    cont  life_exp      gdp_cap
140        1691    Zambia  2007  11746035.0  Africa    42.384  1271.211593
141        1703  Zimbabwe  2007  12311143.0  Africa    43.487   469.709298